[package]
name = "preprocessor-charts"
edition.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
chrono.workspace = true
preprocessor-core = { path = "../preprocessor-core" }
preprocessor-fetch = { path = "../preprocessor-fetch" }
preprocessor-tools = { path = "../preprocessor-tools" }
preprocessor-zip = { path = "../preprocessor-zip" }
serde.workspace = true
serde_json.workspace = true
