[package]
name = "app-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
procedure-geometry-types = { path = "../../../../crates/procedure-geometry-types" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusqlite.workspace = true

[dev-dependencies]
app-fixtures = { path = "../app-fixtures" }
image = "0.25"
