[package]
name = "preprocessor-csup"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde_json.workspace = true
preprocessor-core = { path = "../preprocessor-core" }
preprocessor-fetch = { path = "../preprocessor-fetch" }
preprocessor-tools = { path = "../preprocessor-tools" }
preprocessor-zip = { path = "../preprocessor-zip" }
roxmltree.workspace = true

[dev-dependencies]
tempfile.workspace = true
zip.workspace = true
