[package]
name = "preprocessor-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
chrono.workspace = true
crossbeam-channel.workspace = true
libc = "0.2"
preprocessor-charts = { path = "../preprocessor-charts" }
preprocessor-csup = { path = "../preprocessor-csup" }
preprocessor-data = { path = "../preprocessor-data" }
preprocessor-core = { path = "../preprocessor-core" }
preprocessor-fetch = { path = "../preprocessor-fetch" }
preprocessor-fast = { path = "../preprocessor-fast" }
preprocessor-resource-index = { path = "../preprocessor-resource-index" }
preprocessor-tpp = { path = "../preprocessor-tpp" }
preprocessor-tools = { path = "../preprocessor-tools" }
preprocessor-vectors = { path = "../preprocessor-vectors" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
zip.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tempfile.workspace = true

[build-dependencies]
sha2.workspace = true
