[package]
name = "preprocessor-procedure-geometry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
app-core = { path = "../../../ui/core-rust/crates/app-core" }
procedure-geometry-types = { path = "../../../crates/procedure-geometry-types" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[dev-dependencies]
app-fixtures = { path = "../../../ui/core-rust/crates/app-fixtures" }
image.workspace = true
