import { describe, expect, it } from "vitest";
import { loadBestAvailableAdapter } from "./appCoreAdapter";

const snapshotJson = JSON.stringify({
  app_state: {
    active_plan: null,
    content_policy: "PreferLocal",
    last_content_report: null,
  },
  app_ui_state: {
    active_plan: null,
    ownship: {
      render: {
        mode: "none",
        banner_text: "NO GPS POSITION",
        banner_severity: "warning",
        draw_aircraft: false,
        draw_predictor: false,
        draw_cdi: false,
        position: null,
        orientation_deg: null,
        speed_kt: null,
      },
      controls: {
        mode: "none",
        selection: { kind: "auto" },
        launcher_label: "No GPS",
        launcher_tone: "unavailable",
        launcher_text_tone: "unavailable",
        sources: [],
        situation_controls: [],
      },
    },
    flight_data_banner: { cells: [] },
    content_policy: "PreferLocal",
    last_content_report: null,
  },
  chart_page_state: {
    ordered_airport_ids: [],
    recent_airport_ids: [],
    selected_airport_id: "",
    selected_chart_id: "",
  },
  map_layer_state: {
    world_basemap: { visible: true, enabled: true },
    vectors: { visible: true, enabled: true },
    metars: { visible: true, enabled: true },
    nexrad: { visible: false, enabled: true },
    terrain_warning: { visible: true, enabled: true },
    offline_regions: { visible: false, enabled: true },
  },
  data_status_state: {
    boxes: [],
    launcher_count: null,
    launcher_severity: "info",
  },
  data_status_page_state: {
    title: "Status",
    summary: "All tracked systems are usable.",
    rows: [],
  },
  settings_page_state: {
    title: "Settings",
    summary: "No platform settings are available.",
    rows: [],
  },
  display_policy: null,
  disclaimer_state: {
    agreement_id: "no-warranty-v1",
    required: true,
    html: "<p><strong>NO WARRANTY</strong>: test</p>",
    text: "NO WARRANTY: test",
    accept_label: "I understand and agree",
  },
});

describe("loadBestAvailableAdapter", () => {
  it("fails loudly when the generated wasm module is missing", async () => {
    await expect(loadBestAvailableAdapter(async () => {
      throw new Error("module not found");
    })).rejects.toThrow("module not found");
  });

  it("uses the wasm adapter when the generated module exports the expected API", async () => {
    const loaded = await loadBestAvailableAdapter(async () => ({
      situation_ring_candidates_json: () => "[]",
      empty_flight_plan_json: () => JSON.stringify({ id: "plan-empty", name: "Flight Plan", legs: [], route_components: [], route_component_uids: [], route_component_uid_counter: 0, resolved_legs: [], guidance: null, departure: null, destination: null, alternate: null, cruise_altitude_ft: null, notes: null, updated_at_epoch_ms: 0, version: 1 }),
      create_ui_session: async (_planJson: string, _recentAirportIdsJson: string, _selectedAirportIdJson: string, _selectedChartIdJson: string, _nowEpochMs: number) => {
        return JSON.stringify({ handle: 1, snapshot: JSON.parse(snapshotJson) });
      },
      perform_map_selection_action_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      set_situation_in_session: async () => snapshotJson,
      set_situation_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      tick_bad_autopilot_in_session: async () => snapshotJson,
      tick_bad_autopilot_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      engage_map_follow_in_session: async () => snapshotJson,
      disengage_map_follow_in_session: async () => snapshotJson,
      set_map_follow_offset_in_session: async () => snapshotJson,
      sync_map_follow_in_session: async () => snapshotJson,
      load_playback_trace_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      play_playback_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      pause_playback_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      seek_playback_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      set_playback_rate_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      tick_playback_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      register_ownship_source_in_session: async () => snapshotJson,
      register_ownship_source_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      update_ownship_source_status_in_session: async () => snapshotJson,
      update_ownship_source_status_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      push_situation_sample_in_session: async () => snapshotJson,
      push_situation_sample_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      select_ownship_source_in_session: async () => snapshotJson,
      select_ownship_source_in_session_paged: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      apply_situation_control_input_in_session: async () => snapshotJson,
      set_map_layer_visibility_in_session: async () => snapshotJson,
      set_map_layer_enabled_in_session: async () => snapshotJson,
      set_debug_flag_in_session: async () => snapshotJson,
      accept_disclaimer_in_session: async () => snapshotJson,
      set_resource_policy_in_session: async () => snapshotJson,
      configure_platform_capabilities_in_session: async () => snapshotJson,
      load_raster_map_catalog_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      select_map_family_in_session: async () => snapshotJson,
      select_raster_map_in_session: async () => snapshotJson,
      insert_waypoint_at_flight_plan_row_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      perform_flight_plan_row_action_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      perform_status_action_in_session: async () => snapshotJson,
      sync_guidance_geometry_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      project_flight_plan_route_in_session: async () => JSON.stringify({ state: "complete", result: [] }),
      select_airport_in_session: async () => snapshotJson,
      select_chart_in_session: async () => snapshotJson,
      ingest_point_tiles_in_session: async () => {},
      ingest_airspace_ref_tiles_in_session: async () => {},
      ingest_airspace_features_in_session: async () => {},
      ingest_airspace_label_tiles_in_session: async () => {},
      ingest_resource_in_session: async () => {},
      report_session_resource_failure_in_session: async () => snapshotJson,
      report_session_resource_failure_in_session_at_epoch_ms: async () => snapshotJson,
      resolve_chart_asset_resource_in_session: async () => JSON.stringify({ source: { kind: "unavailable", message: "test" } }),
      get_map_overlay_in_session: async () => "{\"state\":\"complete\",\"result\":{\"visible_features\":[],\"visible_metars\":[],\"visible_pireps\":[],\"airspace_paths\":[],\"tfr_paths\":[],\"airspace_labels\":[]}}",
      get_map_selection_in_session: async () => "{\"state\":\"complete\",\"result\":{\"click_lat\":0,\"click_lon\":0,\"categories\":[]}}",
      get_map_selection_for_nav_ref_in_session: async () => "{\"state\":\"complete\",\"result\":null}",
      get_terrain_overlay_in_session: async () => "{\"needed_terrain_tiles\":[],\"status\":\"hidden\"}",
      get_scheduled_terrain_overlay_in_session: async () => "{\"state\":\"complete\",\"result\":{\"status\":{\"state\":\"hidden\"},\"tile_requests\":[],\"altitude_bucket_ft\":null,\"frame_key\":null,\"schedule\":{\"cached_count\":0,\"in_flight_count\":0,\"missing_count\":0,\"frame_complete\":false,\"work_batch\":[]}}}",
      get_nexrad_overlay_in_session: async () => "{\"state\":\"complete\",\"result\":{\"status\":{\"state\":\"hidden\"},\"tiles\":[]}}",
      get_raster_tile_plan_in_session: async () => "{\"background_color\":\"#000000\",\"layers\":[]}",
      get_raster_tile_plan_in_session_with_display_scale: async () => "{\"background_color\":\"#000000\",\"layers\":[]}",
      render_terrain_overlay_tile_by_key_in_session: async () => new Uint8Array(),
      get_session_snapshot: async () => snapshotJson,
      get_session_snapshot_at_epoch_ms: async () => snapshotJson,
      create_session_snapshot_refresh_scheduler: async () => 1,
      destroy_session_snapshot_refresh_scheduler: async () => {},
      session_snapshot_refresh_scheduler_request: async () => JSON.stringify({ kind: "idle" }),
      session_snapshot_refresh_scheduler_viewport_gesture_active_changed: async () => JSON.stringify({ kind: "idle" }),
      session_snapshot_refresh_scheduler_viewport_activity: async () => JSON.stringify({ kind: "idle" }),
      session_snapshot_refresh_scheduler_refresh_completed: async () => JSON.stringify({ kind: "idle" }),
      session_snapshot_refresh_scheduler_poll: async () => JSON.stringify({ kind: "idle" }),
      restore_chart_page_state_in_session: async () => snapshotJson,
      destroy_session: () => {},
      install_rust_debug_logger: () => {},
      nav_db_open_controller_create: async () => 1,
      nav_db_open_controller_destroy: async () => {},
      nav_db_open_controller_finish: async () => JSON.stringify({ nav_kv_handle: 1, open_result: { selected_package_id: "NAV_DB_2604", selected_filename: "nav_db.zip", statuses: [] } }),
      nav_db_open_controller_ingest_resource: async () => {},
      nav_db_open_controller_step: async () => JSON.stringify({ state: "complete", result: { selected_package_id: "NAV_DB_2604", selected_filename: "nav_db.zip", statuses: [] } }),
      nav_kv_insert_resource: async () => {},
      nav_kv_prefetch_pages: async () => "[]",
      nav_kv_destroy: async () => {},
      attach_nav_kv_store_to_session: async () => {},
      core_had_operation: async () => JSON.stringify({ state: "complete", result: null }),
      sync_live_feeds_in_session: async () => JSON.stringify({ state: "complete", result: { products: [] } }),
      ingest_live_feed_sse_event_in_session: async () => JSON.stringify({ state: "complete", result: { products: [] } }),
      ingest_live_feed_sse_events_in_session: async () => JSON.stringify({ state: "complete", result: { products: [] } }),
      report_live_feed_connection_event_in_session: async () => snapshotJson,
      suggest_waypoint_identifiers_at_flight_plan_row_in_session: async () => JSON.stringify({ state: "complete", result: [] }),
      preview_flight_plan_entry_in_session: async () => JSON.stringify({ state: "complete", result: { can_commit: false, tokens: [], issues: [] } }),
      append_flight_plan_entry_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      insert_airway_at_flight_plan_row_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      select_procedure_at_flight_plan_row_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      load_plate_procedure_in_session: async () => JSON.stringify({ state: "complete", result: JSON.parse(snapshotJson) }),
      activate_next_leg_in_session: async () => snapshotJson,
      suspend_sequencing_in_session: async () => snapshotJson,
      unsuspend_sequencing_in_session: async () => snapshotJson,
      sequence_active_leg_in_session: async () => snapshotJson,
    }));

    expect(loaded.backend).toBe("wasm");
    expect(loaded.detail).toContain("Rust WASM");
  });
});
