import type { CatalogJson, ResourceIndexJson } from "./types";

export const sampleCatalogFixture: CatalogJson = {
  schema_version: 1,
  cycle: "2604",
  catalog_revision: "local-fixture",
  families: [
    { id: "sec", display_name: "Sectional", kind: "chart", max_zoom: 12.5, tile_size: 512 },
    { id: "tac", display_name: "Terminal Area", kind: "chart", max_zoom: 12.5, tile_size: 512 },
    { id: "enr-l", display_name: "IFR Low", kind: "chart", max_zoom: 12.5, tile_size: 512 },
    { id: "enr-h", display_name: "IFR High", kind: "chart", max_zoom: 12.5, tile_size: 512 },
  ],
  regions: [
    { id: "nw", display_name: "Northwest", sort_order: 1 },
  ],
  packages: [
    {
      id: { region: "nw", family: "sec", cycle: "2604" },
      package_name: "SEC_NW_2604",
      family_id: "sec",
      region_id: "nw",
      cycle: "2604",
      artifact_kind: "package",
      relative_url: "sec_nw_2604_01_fixture.zip",
      manifest_name: "SEC_NW_2604.manifest",
      size_bytes: 1,
      checksum_sha256: null,
    },
  ],
  charts: [
    {
      id: { family: "sec", name: "nw", cycle: "2604" },
      family_id: "sec",
      name: "nw",
      display_name: "Northwest Sectional",
      cycle: "2604",
      region_ids: ["nw"],
      max_zoom: 12.5,
      tile_path_template: "tiles/{z}/{x}/{y}.webp",
      coverage: null,
    },
  ],
  plates: [],
  supplements: [],
};

export const sampleResourceIndexFixture: ResourceIndexJson = {
  schema_version: 1,
  cycle: "2604",
  generated_at_utc: "2026-04-24T00:00:00Z",
  families: [
    { id: "sec", display_name: "Sectional", kind: "chart" },
    { id: "tac", display_name: "Terminal Area", kind: "chart" },
    { id: "enr-l", display_name: "IFR Low", kind: "chart" },
    { id: "enr-h", display_name: "IFR High", kind: "chart" },
    { id: "tpp", display_name: "TPP", kind: "documents" },
    { id: "csup", display_name: "Chart Supplement", kind: "documents" },
  ],
  regions: [
    { id: "nw", display_name: "Northwest", sort_order: 1 },
  ],
  packages: [
    {
      id: "SEC_NW_2604_01",
      family_id: "sec",
      region_id: "nw",
      size_bytes: 1,
      checksum_sha256: "fixture",
    },
    {
      id: "TPP_NW_2604_01",
      family_id: "tpp",
      region_id: "nw",
      size_bytes: 1,
      checksum_sha256: "fixture",
    },
  ],
  chart_collections: [
    {
      id: "sec:nw",
      family_id: "sec",
      region_id: "nw",
      package_id: "SEC_NW_2604_01",
      chart_index: 0,
      tile_path_template: "tiles/{z}/{x}/{y}.webp",
      levels: [
        { zoom: 8, x_min: 0, x_max: 255, y_tms_min: 0, y_tms_max: 255 },
        { zoom: 10, x_min: 0, x_max: 1023, y_tms_min: 0, y_tms_max: 1023 },
      ],
      coverage_bounds: {
        lat_min: 41,
        lat_max: 49,
        lon_min: -125,
        lon_max: -116,
      },
      default_view: {
        lat: 46.0,
        lon: -122.0,
        zoom: 8.2,
      },
    },
  ],
  airports: [
    { id: "KRNT", facility_name: "Renton", lat: 47.493, lon: -122.216, airport_type: "airport" },
    { id: "KUAO", facility_name: "Aurora", lat: 45.248, lon: -122.771, airport_type: "airport" },
    { id: "KRDD", facility_name: "Redding", lat: 40.509, lon: -122.293, airport_type: "airport" },
  ],
  airport_resources: [
    {
      airport_id: "KRNT",
      plate_ids: ["KRNT:plate:1"],
      csup_ids: [],
      package_ids: ["TPP_NW_2604_01"],
    },
    {
      airport_id: "KUAO",
      plate_ids: ["KUAO:plate:1"],
      csup_ids: [],
      package_ids: ["TPP_NW_2604_01"],
    },
    {
      airport_id: "KRDD",
      plate_ids: ["KRDD:plate:1"],
      csup_ids: [],
      package_ids: ["TPP_NW_2604_01"],
    },
  ],
  plates: [
    {
      id: "KRNT:plate:1",
      airport_id: "KRNT",
      region_id: "nw",
      package_id: "TPP_NW_2604_01",
      asset_path: "plates/KRNT/IAP-KRNT-RNAV RWY 16.webp",
      thumbnail_path: "thumbnails/KRNT/IAP-KRNT-RNAV RWY 16.webp",
      label: "RNAV 16",
      asset_kind: "plate",
      document_type: "approach",
      georef: null,
    },
    {
      id: "KUAO:plate:1",
      airport_id: "KUAO",
      region_id: "nw",
      package_id: "TPP_NW_2604_01",
      asset_path: "plates/KUAO/APD-KUAO-AIRPORT DIAGRAM.webp",
      thumbnail_path: "thumbnails/KUAO/APD-KUAO-AIRPORT DIAGRAM.webp",
      label: "Airport Diagram",
      asset_kind: "plate",
      document_type: "airport_diagram",
      georef: null,
    },
    {
      id: "KRDD:plate:1",
      airport_id: "KRDD",
      region_id: "nw",
      package_id: "TPP_NW_2604_01",
      asset_path: "plates/KRDD/IAP-KRDD-ILS RWY 34.webp",
      thumbnail_path: "thumbnails/KRDD/IAP-KRDD-ILS RWY 34.webp",
      label: "ILS 34",
      asset_kind: "plate",
      document_type: "approach",
      georef: null,
    },
  ],
  csups: [],
};
